{{- $pipelinesConfig := deepCopy .Values.pipelines.config -}}
{{- $_ := set $pipelinesConfig "tablesDatabase" (deepCopy .Values.api.config.tablesDatabase) -}}
{{- $_ := set $pipelinesConfig.appApi "workerToken" .Values.api.config.pipelines.workerToken -}}
{{- if and $pipelinesConfig.connector.enabled (empty $pipelinesConfig.connector.license) -}}
{{- $_ := set $pipelinesConfig.connector "license" .Values.agent.config.connector.license -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsdiag-app.configName" (dict "root" . "component" "pipelines") }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsdiag-app.podLabels" (dict "root" . "component" "pipelines") | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- include "common.tplvalues.render" (dict "value" ($pipelinesConfig | toYaml) "context" $) | nindent 4 }}
