apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsdiag-app.configName" (dict "root" . "component" "pipelines") }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsdiag-app.podLabels" (dict "root" . "component" "pipelines") | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- include "common.tplvalues.render" (dict "value" (.Values.pipelines.config | toYaml) "context" $) | nindent 4 }}
