{{/* Copyright OpsDiag. All Rights Reserved. SPDX-License-Identifier: APACHE-2.0 */}}
{{- if and (index .Values "pgsql-tables").enabled (index .Values "pgsql-tables").primary.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opsdiag-app.pgsqlTables.serviceAccountName" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsdiag-app.pgsqlTables.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    {{- with .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    {{- with (index .Values "pgsql-tables").primary.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ (index .Values "pgsql-tables").primary.serviceAccount.automountServiceAccountToken }}
{{- end }}
