{{/* Copyright OpsDiag. All Rights Reserved. SPDX-License-Identifier: APACHE-2.0 */}}
{{- if (index .Values "pgsql-tables").enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "opsdiag-app.pgsqlTables.fullname" .) | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsdiag-app.pgsqlTables.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    {{- with .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: pgsql
      port: {{ (index .Values "pgsql-tables").primary.service.ports.pgsql }}
      protocol: TCP
      targetPort: pgsql
  selector:
    {{- include "opsdiag-app.pgsqlTables.selectorLabels" . | nindent 4 }}
{{- end }}
