apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsolving-app.configName" (dict "root" . "component" "sched") }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsolving-app.podLabels" (dict "root" . "component" "sched") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.yaml: |
    {{- include "common.tplvalues.render" (dict "value" (omit .Values.sched.config "connector" | toYaml) "context" $) | nindent 4 }}
    connector:
      {{- with (omit .Values.sched.config.connector "license") }}
      {{- include "common.tplvalues.render" (dict "value" (. | toYaml) "context" $) | nindent 6 }}
      {{- end }}
      license: {{ default .Values.agent.config.connector.license .Values.sched.config.connector.license | quote }}
