{{/* Copyright Opsolving. All Rights Reserved. SPDX-License-Identifier: APACHE-2.0 */}}
{{- if .Values.sched.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opsolving-app.serviceAccountName" (dict "root" . "component" "sched") }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsolving-app.podLabels" (dict "root" . "component" "sched") | nindent 4 }}
  {{- if .Values.sched.serviceAccount.annotations }}
  annotations:
    {{- with .Values.sched.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.sched.serviceAccount.automountServiceAccountToken }}
{{- end }}
