{{/* Copyright Opsolving. All Rights Reserved. SPDX-License-Identifier: APACHE-2.0 */}}
{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opsolving-app.serviceAccountName" (dict "root" . "component" "api") }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsolving-app.podLabels" (dict "root" . "component" "api") | nindent 4 }}
  {{- if or .Values.api.migration.enabled .Values.api.serviceAccount.annotations }}
  annotations:
    {{- if .Values.api.migration.enabled }}
    argocd.argoproj.io/sync-wave: "-11"
    {{- end }}
    {{- with .Values.api.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.api.serviceAccount.automountServiceAccountToken }}
{{- end }}
