apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opsdiag-connector.configMapName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    license: ""
    licenseServer: {{ .Values.connector.licenseServer | quote }}
    gatewayURL: {{ .Values.connector.gatewayURL | quote }}
