apiVersion: v2
name: opsolving-app-connector
description: Opsolving customer-side app connector
type: application
version: 1.0.1
appVersion: "2026-08-11.02-13-59.d3f3a70"
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.31.4
