{{- if and .Values.api.enabled .Values.api.schedulerWorkerToken.value (not .Values.api.schedulerWorkerToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsdiag-app.schedulerWorkerTokenSecretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsdiag-app.podLabels" (dict "root" . "component" "api") | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.api.schedulerWorkerToken.key | quote }}: {{ .Values.api.schedulerWorkerToken.value | quote }}
{{- end }}
