apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsdiag-app.configName" (dict "root" . "component" "api") }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsdiag-app.podLabels" (dict "root" . "component" "api") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.yaml: |
    {{- include "common.tplvalues.render" (dict "value" (omit .Values.api.config "database" "tablesDatabase" | toYaml) "context" $) | nindent 4 }}
    database:
      {{- with (omit .Values.api.config.database "url") }}
      {{- include "common.tplvalues.render" (dict "value" (. | toYaml) "context" $) | nindent 6 }}
      {{- end }}
      url: {{ include "opsdiag-app.pgsql.url" . | quote }}
    tablesDatabase:
      {{- with (omit .Values.api.config.tablesDatabase "url") }}
      {{- include "common.tplvalues.render" (dict "value" (. | toYaml) "context" $) | nindent 6 }}
      {{- end }}
      url: {{ include "opsdiag-app.pgsqlTables.url" . | quote }}
