{{/* Copyright Opsolving. All Rights Reserved. SPDX-License-Identifier: APACHE-2.0 */}}
{{- if and (index .Values "pgsql-tables").enabled (not (index .Values "pgsql-tables").auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsolving-app.pgsqlTables.secretName" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsolving-app.pgsqlTables.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    {{- with .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{ required "pgsql-tables.auth.secretKeys.userPasswordKey is required" (index .Values "pgsql-tables").auth.secretKeys.userPasswordKey }}: {{ required "pgsql-tables.auth.password is required when auth.existingSecret is empty" (index .Values "pgsql-tables").auth.password | quote }}
{{- end }}
