apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsdiag-app.configName" (dict "root" . "component" "vcs") }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsdiag-app.podLabels" (dict "root" . "component" "vcs") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.yaml: |
    {{- include "common.tplvalues.render" (dict "value" (.Values.vcs.config | toYaml) "context" $) | nindent 4 }}
