{{/* Copyright OpsDiag. All Rights Reserved. SPDX-License-Identifier: APACHE-2.0 */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsdiag-app.componentName" (dict "root" . "component" "vcs") }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsdiag-app.podLabels" (dict "root" . "component" "vcs") | nindent 4 }}
  {{- with .Values.vcs.service.annotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.vcs.service.type }}
  {{- with .Values.vcs.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.vcs.service.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "opsdiag-app.selectorLabels" (dict "root" . "component" "vcs") | nindent 4 }}
