apiVersion: v2
name: opsdiag-app-connector
description: OpsDiag customer-side app connector
type: application
version: 0.2.16
appVersion: "2026-08-10.23-11-17.9500e05"
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.31.4
