{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
  {{- if or .Values.istio.annotations .Values.istio.virtualService.annotations .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.merge" (dict "values" (list .Values.istio.virtualService.annotations .Values.istio.annotations .Values.commonAnnotations) "context" .) | nindent 4 }}
  {{- end }}
spec:
  hosts:
    {{- concat (list (tpl (required "istio.hostname is required when istio.enabled is true" .Values.istio.hostname) .)) (.Values.istio.extraHosts | default (list)) | toYaml | nindent 4 }}
  gateways:
    - {{ printf "%s-gateway" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  http:
    - name: apisix-gateway
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "opsolving-app.apisixServiceName" . }}
            port:
              number: {{ include "opsolving-app.apisixServicePort" . }}
{{- end }}
