{{/* Copyright OpsDiag. All Rights Reserved. SPDX-License-Identifier: Apache-2.0 */}}

{{- include "opsdiag-app.validateApisix" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ required "apisix.apisix.deployment.standalone.existingConfigMap is required" .Values.apisix.apisix.deployment.standalone.existingConfigMap | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
data:
  apisix.yaml: |
    routes:
    {{- range $route := .Values.gateway.routing.routes }}
      - id: {{ $route.id | quote }}
        name: {{ default $route.id $route.name | quote }}
        uris:
          {{- $route.uris | toYaml | nindent 10 }}
        priority: {{ int $route.priority }}
        {{- if $route.enableWebsocket }}
        enable_websocket: true
        {{- end }}
        upstream:
          type: roundrobin
          scheme: http
          pass_host: pass
          {{- with index $.Values.gateway.routing.upstreams $route.upstream }}
          timeout:
            connect: {{ int .timeout.connect }}
            send: {{ int .timeout.send }}
            read: {{ int .timeout.read }}
          nodes:
            {{ printf "%s:%v" (include "opsdiag-app.componentServiceName" (dict "root" $ "component" .component)) (index $.Values .component).service.ports.http | quote }}: 1
          {{- end }}
    {{- end }}
    #END
