apiVersion: v2
name: opsdiag-app
description: Complete OpsDiag application stack
type: application
version: 0.1.8
appVersion: "2026-07-19"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-app-api
  - https://github.com/presemantic/opsdiag-app-agent-api
  - https://github.com/presemantic/opsdiag-app-front
  - https://github.com/presemantic/opsdiag-app-sched
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
