apiVersion: v2
name: opsdiag-app
description: Complete OpsDiag application stack
type: application
version: 0.3.2
appVersion: "2026-08-10"
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
  - name: apisix
    repository: https://charts.apiseven.com
    version: 2.16.0
