apiVersion: v2
name: opsdiag-app
description: Complete OpsDiag application stack
type: application
version: 0.2.0
appVersion: "2026-08-09"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-app-api
  - https://github.com/presemantic/opsdiag-app-agent-api
  - https://github.com/presemantic/opsdiag-app-front
  - https://github.com/presemantic/opsdiag-app-sched
  - https://github.com/presemantic/opsdiag-app-pipelines
  - https://github.com/presemantic/opsdiag-app-mcp-proxy-api
  - https://github.com/presemantic/opsdiag-app-vcs-api
  - https://github.com/apache/apisix
  - https://github.com/apache/apisix-helm-chart
  - https://github.com/docker-library/postgres
  - https://www.postgresql.org
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
  - name: apisix
    repository: https://charts.apiseven.com
    version: 2.16.0
