{{/* Copyright OpsDiag. All Rights Reserved. SPDX-License-Identifier: APACHE-2.0 */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsdiag-app.componentName" (dict "root" . "component" "front") }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsdiag-app.podLabels" (dict "root" . "component" "front") | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.front.replicaCount }}
  revisionHistoryLimit: {{ .Values.front.revisionHistoryLimit }}
  strategy:
    {{- include "common.tplvalues.render" (dict "value" .Values.front.updateStrategy "context" .) | nindent 4 }}
  selector:
    matchLabels:
      {{- include "opsdiag-app.selectorLabels" (dict "root" . "component" "front") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opsdiag-app.podLabels" (dict "root" . "component" "front") | nindent 8 }}
      {{- with .Values.front.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "opsdiag-app.serviceAccountName" (dict "root" . "component" "front") }}
      automountServiceAccountToken: {{ .Values.front.serviceAccount.automountServiceAccountToken }}
      {{- include "common.images.renderPullSecrets" (dict "images" (list .Values.front.image) "context" .) | nindent 6 }}
      {{- if .Values.front.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.front.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.front.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.front.schedulerName }}
      schedulerName: {{ . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.front.terminationGracePeriodSeconds }}
      {{- with .Values.front.nodeSelector }}
      nodeSelector:
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.front.affinity }}
      affinity:
        {{- include "common.tplvalues.render" (dict "value" .Values.front.affinity "context" .) | nindent 8 }}
      {{- else if or .Values.front.podAffinityPreset .Values.front.podAntiAffinityPreset .Values.front.nodeAffinityPreset.type }}
      affinity:
        {{- if .Values.front.podAffinityPreset }}
        podAffinity:
          {{- include "common.affinities.pods" (dict "type" .Values.front.podAffinityPreset "component" "front" "customLabels" .Values.front.podLabels "context" .) | nindent 10 }}
        {{- end }}
        {{- if .Values.front.podAntiAffinityPreset }}
        podAntiAffinity:
          {{- include "common.affinities.pods" (dict "type" .Values.front.podAntiAffinityPreset "component" "front" "customLabels" .Values.front.podLabels "context" .) | nindent 10 }}
        {{- end }}
        {{- if .Values.front.nodeAffinityPreset.type }}
        nodeAffinity:
          {{- include "common.affinities.nodes" (dict "type" .Values.front.nodeAffinityPreset.type "key" .Values.front.nodeAffinityPreset.key "values" .Values.front.nodeAffinityPreset.values) | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.front.tolerations }}
      tolerations:
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- with .Values.front.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: "front"
          image: {{ include "common.images.image" (dict "imageRoot" .Values.front.image "global" .Values.global "chart" .Chart) | quote }}
          imagePullPolicy: {{ .Values.front.image.pullPolicy }}
          {{- if .Values.front.containerSecurityContext.enabled }}
          securityContext:
            {{- omit .Values.front.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.front.containerPorts.http }}
              protocol: TCP
          {{- with .Values.front.extraEnvVars }}
          env:
            {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
          {{- end }}
          {{- if or .Values.front.extraEnvVarsCM .Values.front.extraEnvVarsSecret }}
          envFrom:
            {{- with .Values.front.extraEnvVarsCM }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- with .Values.front.extraEnvVarsSecret }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- end }}
          {{- with .Values.front.resources }}
          resources:
            {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.front.livenessProbe.enabled }}
          livenessProbe:
            {{- include "common.tplvalues.render" (dict "value" .Values.front.livenessProbe.spec "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.front.readinessProbe.enabled }}
          readinessProbe:
            {{- include "common.tplvalues.render" (dict "value" .Values.front.readinessProbe.spec "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.front.startupProbe.enabled }}
          startupProbe:
            {{- include "common.tplvalues.render" (dict "value" .Values.front.startupProbe.spec "context" .) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-tmp
              mountPath: /tmp
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}
