{{/* Copyright OpsDiag. All Rights Reserved. SPDX-License-Identifier: APACHE-2.0 */}}
{{- if (index .Values "mcp-proxy").serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opsdiag-app.serviceAccountName" (dict "root" . "component" "mcp-proxy") }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsdiag-app.podLabels" (dict "root" . "component" "mcp-proxy") | nindent 4 }}
  {{- if (index .Values "mcp-proxy").serviceAccount.annotations }}
  annotations:
    {{- with (index .Values "mcp-proxy").serviceAccount.annotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ (index .Values "mcp-proxy").serviceAccount.automountServiceAccountToken }}
{{- end }}
