apiVersion: v2
name: opsdiag-app-api
description: OpsDiag app API
type: application
version: 0.1.7
appVersion: "2026-07-17.10-19-08.00ef0a7"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-app-api
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
