apiVersion: v2
name: opsdiag-app-api
description: OpsDiag app API
type: application
version: 0.1.14
appVersion: "2026-07-18.22-10-12.bec3c6c"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-app-api
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
