{{/* Copyright OpsDiag. All Rights Reserved. SPDX-License-Identifier: APACHE-2.0 */}}
{{- if and .Values.pgsql.enabled (not .Values.pgsql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsdiag-app.pgsql.secretName" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsdiag-app.pgsql.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    {{- with .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{ required "pgsql.auth.secretKeys.userPasswordKey is required" .Values.pgsql.auth.secretKeys.userPasswordKey }}: {{ required "pgsql.auth.password is required when auth.existingSecret is empty" .Values.pgsql.auth.password | quote }}
{{- end }}
