apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsolving-app.configName" (dict "root" . "component" "pipelines") }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "opsolving-app.podLabels" (dict "root" . "component" "pipelines") | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- include "common.tplvalues.render" (dict "value" (omit .Values.pipelines.config "database" "tablesDatabase" "appApi" "connector" | toYaml) "context" $) | nindent 4 }}
    database:
      {{- with (omit .Values.pipelines.config.database "url") }}
      {{- include "common.tplvalues.render" (dict "value" (. | toYaml) "context" $) | nindent 6 }}
      {{- end }}
      url: {{ include "opsolving-app.pgsql.url" . | quote }}
    tablesDatabase:
      url: {{ include "opsolving-app.pgsqlTables.url" . | quote }}
    appApi:
      {{- with .Values.pipelines.config.appApi }}
      {{- include "common.tplvalues.render" (dict "value" (. | toYaml) "context" $) | nindent 6 }}
      {{- end }}
    connector:
      {{- with (omit .Values.pipelines.config.connector "license") }}
      {{- include "common.tplvalues.render" (dict "value" (. | toYaml) "context" $) | nindent 6 }}
      {{- end }}
      license: {{ default .Values.agent.config.connector.license .Values.pipelines.config.connector.license | quote }}
