apiVersion: v2
name: opsdiag-app-agent
description: OpsDiag app agent API
type: application
version: 0.1.7
appVersion: "2026-07-15.06-36-20.a50b49e"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-app-agent-api
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
