apiVersion: v2
name: opsdiag-connector
description: OpsDiag customer-side gateway connector
type: application
version: 0.1.0
appVersion: "2026-06-21.01-08-55.fd309e"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-gateway-connector
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
