apiVersion: v2
name: opsdiag-app-front
description: OpsDiag app frontend
type: application
version: 0.1.5
appVersion: "2026-07-17.14-28-50.8c2593b"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-app-front
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
