apiVersion: v2
name: opsdiag-app-front
description: OpsDiag app frontend
type: application
version: 0.1.2
appVersion: "2026-07-13.13-01-08.cd9a2e8"
home: https://opsdiag.ai
sources:
  - https://github.com/presemantic/opsdiag-app-front
dependencies:
  - name: common
    repository: https://opsolving.github.io/charts/
    version: 2.x.x
