{{- if and .Values.connector.license (not .Values.connector.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsdiag-connector.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.connector.existingSecretKey }}: {{ .Values.connector.license | b64enc | quote }}
{{- end }}
