name: "opsdiag-helm-pub"

on:
  workflow_dispatch:
    inputs:
      VERSION_TAG:
        description: Version tag to package, if not set latest timestamp tag will be used
        required: true
        type: string
        default: '2025-01-01.01-01-01.aaaaaa'
  push:
    tags:
      - '20*'

permissions:
  contents: read

env:
  REGION: europe-west1
  GAR_LOCATION: europe-west1-docker.pkg.dev/prod-common-cicd/opsdiag-helm-pub

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chart:
          - opsdiag-app
          - opsdiag-app-connector
    steps:
      - name: "[Checkout] Build"
        uses: actions/checkout@v4
        with:
          path: build

      - name: "[Versioner] Get version from latest tag"
        working-directory: build
        env:
          MANUAL_VERSION_TAG: ${{ github.event.inputs.VERSION_TAG }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_REF_TYPE: ${{ github.ref_type }}
        run: |
          set -euo pipefail
          base_version_regex='^[0-9]{4}-[0-9]{2}-[0-9]{2}\.[0-9]{2}-[0-9]{2}-[0-9]{2}\.[0-9a-z]+$'

          if [ "${GITHUB_REF_TYPE}" = "tag" ] && [[ "${GITHUB_REF_NAME}" =~ ${base_version_regex} ]]; then
            VERSION_TAG="${GITHUB_REF_NAME}"
          elif [ -n "${MANUAL_VERSION_TAG}" ] && [[ "${MANUAL_VERSION_TAG}" =~ ${base_version_regex} ]]; then
            VERSION_TAG="${MANUAL_VERSION_TAG}"
          else
            git fetch --tags
            VERSION_TAG="$(git tag --sort=committerdate | grep -Ei "${base_version_regex}" | tail -1)"
          fi

          if [ -z "${VERSION_TAG}" ]; then
            echo "Tag not found"
            exit 1
          fi

          echo "VERSION_TAG=${VERSION_TAG}" >>"${GITHUB_ENV}"

      - name: "[Versioner] Print fetch version"
        run: |
          echo "Version fetched: ${{ env.VERSION_TAG }}"

      - name: "[Checkout] Checkout to Tag"
        uses: actions/checkout@v4
        with:
          path: build
          ref: ${{ env.VERSION_TAG }}

      - name: "[Helm] Setup"
        uses: azure/setup-helm@v4

      - name: "[GOOGLE] Setup Credentials"
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_ARTIFACT_REGISTRY_KEY }}"
          token_format: "access_token"

      - name: "[GOOGLE] Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "[GOOGLE] Use gcloud CLI"
        run: "gcloud info"

      - name: "[Helm] Registry auth"
        run: |
          echo "${{ steps.gcp-auth.outputs.access_token }}" | helm registry login \
            -u oauth2accesstoken \
            --password-stdin \
            "${{ env.REGION }}-docker.pkg.dev"

      - name: "[Helm] Dependency update"
        run: |
          helm dependency update "build/${{ matrix.chart }}"

      - name: "[Helm] Lint"
        run: |
          helm lint "build/${{ matrix.chart }}"

      - name: "[Helm] Package"
        run: |
          mkdir -p dist
          helm package "build/${{ matrix.chart }}" --destination dist

      - name: "[Helm] Push"
        run: |
          helm push dist/${{ matrix.chart }}-*.tgz "oci://${GAR_LOCATION}"
